name: Release to public npm
run-name: "Release (${{ inputs.bump }})"

on:
  workflow_dispatch:
    inputs:
      bump:
        description: Version bump type
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

permissions:
  contents: write

jobs:
  release:
    uses: mafintosh/actions/.github/workflows/public-publish.yml@review
    with:
      bump: ${{ inputs.bump }}
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
